[package]
name = "bugeutils"
version = "0.1.0"
authors = ["Gustavo Moitinho Trindade <gustavo.moitinho@outlook.com>"]
edition = "2018"

[lib]
name = "bugeutils"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/example.rs"

[dependencies]
